name = "guitar-sync"
main = "src/worker.js"
compatibility_date = "2024-09-23"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "guitar-sync"
database_id = "4bde485e-a1fa-4ee3-ae78-99f478fd299b"
